import type { Lab, Mentor } from "@/types";

export const labs: Lab[] = [
  {
    id: "lab-001",
    professor: "김재원 교수",
    university: "KAIST",
    department: "전산학부",
    researchArea: "자연어처리, LLM",
    researchAreaTags: ["자연어처리", "LLM", "멀티모달"],
    mentorCount: 8,
    tags: ["인건비 우수", "논문 실적 우수", "해외 학회 지원"],
    slug: "kaist-cs-kim",
  },
  {
    id: "lab-002",
    professor: "이승훈 교수",
    university: "KAIST",
    department: "전기및전자공학부",
    researchArea: "반도체설계, SoC",
    researchAreaTags: ["반도체설계", "SoC", "VLSI"],
    mentorCount: 6,
    tags: ["체계적 지도", "졸업 후 대기업 多", "주 1회 미팅"],
    slug: "kaist-ee-lee",
  },
  {
    id: "lab-003",
    professor: "박민준 교수",
    university: "서울대",
    department: "컴퓨터공학부",
    researchArea: "컴퓨터비전, 의료AI",
    researchAreaTags: ["컴퓨터비전", "의료AI", "딥러닝"],
    mentorCount: 10,
    tags: ["박사 진학률 높음", "산학 프로젝트 多", "자유로운 분위기"],
    slug: "snu-cs-park",
  },
  {
    id: "lab-004",
    professor: "최동현 교수",
    university: "서울대",
    department: "전기정보공학부",
    researchArea: "로보틱스, 강화학습",
    researchAreaTags: ["로보틱스", "강화학습", "제어"],
    mentorCount: 7,
    tags: ["인건비 양호", "해외 학회 지원", "타대 지원자 환영"],
    slug: "snu-ee-choi",
  },
  {
    id: "lab-005",
    professor: "정수연 교수",
    university: "연세대",
    department: "컴퓨터과학과",
    researchArea: "분산시스템, 클라우드",
    researchAreaTags: ["분산시스템", "클라우드", "인프라"],
    mentorCount: 5,
    tags: ["워라밸 보장", "인건비 양호", "학부 연구 경험 우대"],
    slug: "yonsei-cs-jung",
  },
  {
    id: "lab-006",
    professor: "한지훈 교수",
    university: "연세대",
    department: "전기전자공학부",
    researchArea: "신호처리, 통신",
    researchAreaTags: ["신호처리", "통신", "5G/6G"],
    mentorCount: 6,
    tags: ["체계적 지도", "논문 실적 우수", "주 1회 미팅"],
    slug: "yonsei-ee-han",
  },
  {
    id: "lab-007",
    professor: "윤상준 교수",
    university: "포스텍",
    department: "컴퓨터공학과",
    researchArea: "보안, 시스템소프트웨어",
    researchAreaTags: ["보안", "시스템소프트웨어", "OS"],
    mentorCount: 5,
    tags: ["자유로운 분위기", "인건비 우수", "코딩 테스트 중요"],
    slug: "postech-cs-yun",
  },
  {
    id: "lab-008",
    professor: "조영민 교수",
    university: "포스텍",
    department: "기계공학과",
    researchArea: "자율주행, 제어",
    researchAreaTags: ["자율주행", "제어", "임베디드"],
    mentorCount: 6,
    tags: ["산학 프로젝트 多", "졸업 후 대기업 多", "인건비 양호"],
    slug: "postech-me-cho",
  },
  {
    id: "lab-009",
    professor: "강태영 교수",
    university: "UNIST",
    department: "AI대학원",
    researchArea: "그래프신경망, 추천시스템",
    researchAreaTags: ["그래프신경망", "추천시스템", "GNN"],
    mentorCount: 7,
    tags: ["인건비 양호", "논문 실적 우수", "타대 지원자 환영"],
    slug: "unist-ai-kang",
  },
  {
    id: "lab-010",
    professor: "임재혁 교수",
    university: "UNIST",
    department: "전기전자공학부",
    researchArea: "배터리, 에너지재료",
    researchAreaTags: ["배터리", "에너지재료", "전기화학"],
    mentorCount: 8,
    tags: ["체계적 지도", "해외 학회 지원", "박사 진학률 높음"],
    slug: "unist-ee-lim",
  },
  {
    id: "lab-011",
    professor: "신현우 교수",
    university: "고려대",
    department: "컴퓨터학과",
    researchArea: "바이오인포매틱스",
    researchAreaTags: ["바이오인포매틱스", "유전체분석", "머신러닝"],
    mentorCount: 5,
    tags: ["워라밸 보장", "자유로운 분위기", "학부 연구 경험 우대"],
    slug: "korea-cs-shin",
  },
  {
    id: "lab-012",
    professor: "오지은 교수",
    university: "성균관대",
    department: "소프트웨어학과",
    researchArea: "소프트웨어공학, DevOps",
    researchAreaTags: ["소프트웨어공학", "DevOps", "품질관리"],
    mentorCount: 6,
    tags: ["인건비 양호", "산학 프로젝트 多", "타대 지원자 환영"],
    slug: "skku-sw-oh",
  },
];

export const mentors: Mentor[] = [
  // lab-001 (KAIST 전산)
  {
    id: "mentor-001",
    labId: "lab-001",
    nickname: "KAIST 대학원생 #07",
    cardType: "A",
    researchArea: "자연어처리",
    degree: "PhD",
    yearsInLab: 3,
    consultTopics: ["메일작성법", "타이밍", "후속연락", "교수성향파악"],
    rating: 4.8,
    consultCount: 31,
    intro:
      "저는 3개 연구실 컨택 후 모두 면담까지 진행했어요. 메일 제목부터 본문 구조, 보내는 시기까지 알려드릴게요. 타대 출신이라 더 전략적으로 접근해야 했던 경험이 있습니다.",
  },
  {
    id: "mentor-002",
    labId: "lab-001",
    nickname: "KAIST 대학원생 #13",
    cardType: "B",
    researchArea: "LLM, 멀티모달",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["교수성격", "랩분위기", "인건비", "워라밸", "졸업요건"],
    rating: 4.6,
    consultCount: 19,
    intro:
      "연구실 들어오기 전엔 아무도 알려주지 않는 것들이 있어요. 인건비 실수령액, 교수님이 실제로 어떤 분인지, 야근 문화... 직접 겪은 내용을 솔직하게 공유합니다.",
  },
  // lab-002 (KAIST 전전)
  {
    id: "mentor-003",
    labId: "lab-002",
    nickname: "KAIST 대학원생 #22",
    cardType: "C",
    researchArea: "반도체설계",
    degree: "PhD",
    yearsInLab: 4,
    consultTopics: ["졸업후진로", "취업", "박사진학", "산학협력", "스펙관리"],
    rating: 4.9,
    consultCount: 47,
    intro:
      "저희 랩 졸업생 대부분이 삼성전자·SK하이닉스 전공의로 갔어요. 어느 직군 지원할지, 논문은 몇 편이 필요한지 솔직히 말씀드릴게요.",
  },
  {
    id: "mentor-004",
    labId: "lab-002",
    nickname: "KAIST 대학원생 #35",
    cardType: "D",
    researchArea: "SoC, VLSI",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["학점낮음", "스펙부족", "타대지원", "현실조언", "멘탈관리"],
    rating: 4.5,
    consultCount: 12,
    intro:
      "서울권도 아니고, 학점도 3.3대였어요. 그래도 KAIST 들어왔습니다. 연구 경험 없어도 어떻게 포트폴리오를 만들었는지, 면담에서 뭘 말했는지 다 얘기해드려요.",
  },
  // lab-003 (서울대 컴공)
  {
    id: "mentor-005",
    labId: "lab-003",
    nickname: "서울대 대학원생 #04",
    cardType: "A",
    researchArea: "컴퓨터비전",
    degree: "PhD",
    yearsInLab: 3,
    consultTopics: ["메일작성법", "포트폴리오", "연구경험부족", "면담준비"],
    rating: 4.7,
    consultCount: 28,
    intro:
      "의료 AI 쪽은 교수님들이 실력보다 태도를 많이 보는 편이에요. 메일에서 어떤 점을 어필해야 답장 받을 수 있는지, 면담에서 어떻게 준비했는지 공유합니다.",
  },
  {
    id: "mentor-006",
    labId: "lab-003",
    nickname: "서울대 대학원생 #18",
    cardType: "C",
    researchArea: "의료AI",
    degree: "MS/PhD",
    yearsInLab: 2,
    consultTopics: ["졸업후진로", "취업", "의료스타트업", "해외박사"],
    rating: 4.4,
    consultCount: 9,
    intro:
      "의료 AI 분야 졸업 후 진로가 궁금하시죠? 병원 기업부설연구소, 헬스케어 스타트업, 해외 박사 진학까지 최근 선배들의 실제 현황을 알려드려요.",
  },
  // lab-004 (서울대 전기)
  {
    id: "mentor-007",
    labId: "lab-004",
    nickname: "서울대 대학원생 #09",
    cardType: "B",
    researchArea: "강화학습",
    degree: "PhD",
    yearsInLab: 4,
    consultTopics: ["교수성격", "랩분위기", "인건비", "연구방향"],
    rating: 4.8,
    consultCount: 33,
    intro:
      "로보틱스 랩은 실험 장비 때문에 야근이 잦을 수 있어요. 우리 랩이 실제로 어떤지, 교수님과 주로 어떻게 소통하는지 가감 없이 말씀드립니다.",
  },
  {
    id: "mentor-008",
    labId: "lab-004",
    nickname: "서울대 대학원생 #27",
    cardType: "D",
    researchArea: "로보틱스, 제어",
    degree: "MS",
    yearsInLab: 1,
    consultTopics: ["타대지원", "학점낮음", "현실조언", "연구경험없음"],
    rating: 4.3,
    consultCount: 6,
    intro:
      "지방 사립대 출신으로 서울대 대학원에 입학했어요. 처음엔 학벌 컴플렉스가 있었는데, 실제로 들어와보니 생각보다 다양한 배경의 분들이 있더라고요.",
  },
  // lab-005 (연세대 컴과)
  {
    id: "mentor-009",
    labId: "lab-005",
    nickname: "연세대 대학원생 #11",
    cardType: "A",
    researchArea: "분산시스템",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["메일작성법", "타이밍", "인터뷰준비", "과제제출"],
    rating: 4.6,
    consultCount: 17,
    intro:
      "시스템 분야 교수님들은 메일보다 직접 찾아가는 걸 더 선호하시는 경우가 많아요. 컨택 전략이 다른 분야와 다릅니다. 제가 어떻게 했는지 알려드릴게요.",
  },
  {
    id: "mentor-010",
    labId: "lab-005",
    nickname: "연세대 대학원생 #23",
    cardType: "B",
    researchArea: "클라우드, 인프라",
    degree: "PhD",
    yearsInLab: 3,
    consultTopics: ["워라밸", "랩분위기", "인건비", "졸업요건", "자유도"],
    rating: 4.7,
    consultCount: 25,
    intro:
      "우리 랩은 주 1회 전체 미팅, 평소엔 자율적으로 연구해요. 교수님이 학생 의견을 많이 존중하는 편이고, 야근 강요는 없어요. 실제 생활 패턴을 솔직하게 공유합니다.",
  },
  // lab-006 (연세대 전전)
  {
    id: "mentor-011",
    labId: "lab-006",
    nickname: "연세대 대학원생 #31",
    cardType: "C",
    researchArea: "신호처리, 5G",
    degree: "PhD",
    yearsInLab: 5,
    consultTopics: ["졸업후진로", "통신사취업", "해외유학", "박사과정"],
    rating: 4.9,
    consultCount: 42,
    intro:
      "통신 분야 박사는 SKT·KT 연구소, ETRI, 삼성리서치 등으로 많이 가요. 졸업 논문 수준과 실제 취업 결과의 상관관계, 요즘 채용 트렌드를 알려드립니다.",
  },
  {
    id: "mentor-012",
    labId: "lab-006",
    nickname: "연세대 대학원생 #08",
    cardType: "A",
    researchArea: "통신, 신호처리",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["메일작성법", "연구계획서", "면담질문", "교수확인"],
    rating: 4.5,
    consultCount: 14,
    intro:
      "교수님께 처음 컨택 메일을 보낼 때 연구계획서를 같이 보내야 할지 고민하시죠? 분야마다 다른 관행을 제 경험을 바탕으로 알려드려요.",
  },
  // lab-007 (포스텍 컴공)
  {
    id: "mentor-013",
    labId: "lab-007",
    nickname: "포스텍 대학원생 #16",
    cardType: "B",
    researchArea: "시스템보안",
    degree: "PhD",
    yearsInLab: 4,
    consultTopics: ["교수성격", "랩분위기", "포항생활", "인건비", "해외인턴"],
    rating: 4.7,
    consultCount: 29,
    intro:
      "포스텍은 도시와 멀어서 생활 적응이 중요해요. 연구실 분위기와 교수님 스타일, 그리고 포항에서의 실제 생활을 솔직하게 공유합니다.",
  },
  {
    id: "mentor-014",
    labId: "lab-007",
    nickname: "포스텍 대학원생 #29",
    cardType: "D",
    researchArea: "OS, 보안",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["코딩테스트", "스펙부족", "비전공자", "현실조언"],
    rating: 4.4,
    consultCount: 11,
    intro:
      "보안 쪽은 코딩 테스트와 개인 프로젝트가 정말 중요해요. 학점이 높지 않아도 깃허브 포트폴리오로 뒤집은 경험을 공유합니다.",
  },
  // lab-008 (포스텍 기계)
  {
    id: "mentor-015",
    labId: "lab-008",
    nickname: "포스텍 대학원생 #05",
    cardType: "C",
    researchArea: "자율주행",
    degree: "PhD",
    yearsInLab: 3,
    consultTopics: ["졸업후진로", "자동차회사", "스타트업", "해외박사"],
    rating: 4.8,
    consultCount: 36,
    intro:
      "자율주행 분야 졸업 후 현대·기아 R&D, 라이다 스타트업, 해외 박사로 나뉘어요. 각각 어떤 준비가 필요한지, 저희 랩 선배들의 사례를 알려드립니다.",
  },
  {
    id: "mentor-016",
    labId: "lab-008",
    nickname: "포스텍 대학원생 #38",
    cardType: "A",
    researchArea: "제어, 임베디드",
    degree: "MS",
    yearsInLab: 1,
    consultTopics: ["메일작성법", "면담질문", "연구실선택", "GPA가중치"],
    rating: 4.3,
    consultCount: 5,
    intro:
      "기계공학 교수님들은 수치해석이나 CAD 경험을 보는 분도 있고, 코딩 능력을 더 보는 분도 있어요. 교수님별 성향 파악이 컨택 성패를 가릅니다.",
  },
  // lab-009 (UNIST AI)
  {
    id: "mentor-017",
    labId: "lab-009",
    nickname: "UNIST 대학원생 #14",
    cardType: "B",
    researchArea: "그래프신경망",
    degree: "PhD",
    yearsInLab: 3,
    consultTopics: ["교수성격", "랩분위기", "울산생활", "인건비", "해외학회"],
    rating: 4.6,
    consultCount: 22,
    intro:
      "UNIST는 인건비가 타 학교 대비 높은 편이고, 해외 학회 지원도 활발해요. 교수님이 어떤 분인지, 실제 연구 환경이 어떤지 솔직하게 말씀드릴게요.",
  },
  {
    id: "mentor-018",
    labId: "lab-009",
    nickname: "UNIST 대학원생 #02",
    cardType: "C",
    researchArea: "추천시스템",
    degree: "MS/PhD",
    yearsInLab: 4,
    consultTopics: ["네이버취업", "카카오취업", "스타트업", "박사진학"],
    rating: 4.7,
    consultCount: 31,
    intro:
      "추천시스템 쪽은 네이버·카카오에서 계속 채용 중이에요. GNN 논문 1편 있으면 서류는 거의 통과됩니다. 실제 채용 과정에서 어떤 걸 봤는지 공유합니다.",
  },
  // lab-010 (UNIST 전전)
  {
    id: "mentor-019",
    labId: "lab-010",
    nickname: "UNIST 대학원생 #20",
    cardType: "A",
    researchArea: "배터리 소재",
    degree: "PhD",
    yearsInLab: 4,
    consultTopics: ["메일작성법", "연구경험", "학점기준", "추천서"],
    rating: 4.8,
    consultCount: 38,
    intro:
      "에너지 소재 분야는 실험 경험이 있으면 확실히 유리해요. 없어도 어떻게 강점을 어필할 수 있는지, 교수님께 어떤 내용으로 메일을 썼는지 공유합니다.",
  },
  {
    id: "mentor-020",
    labId: "lab-010",
    nickname: "UNIST 대학원생 #33",
    cardType: "D",
    researchArea: "전기화학",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["비이공계배경", "전과생", "기초부족", "따라잡기"],
    rating: 4.2,
    consultCount: 8,
    intro:
      "화학과 출신으로 전기전자 대학원에 왔어요. 처음엔 기초가 부족해서 힘들었지만, 결국 적응했습니다. 비슷한 상황이라면 도움이 될 거예요.",
  },
  // lab-011 (고려대 컴학)
  {
    id: "mentor-021",
    labId: "lab-011",
    nickname: "고려대 대학원생 #06",
    cardType: "C",
    researchArea: "바이오인포매틱스",
    degree: "PhD",
    yearsInLab: 4,
    consultTopics: ["제약회사", "바이오스타트업", "해외포닥", "논문전략"],
    rating: 4.7,
    consultCount: 26,
    intro:
      "바이오인포 졸업 후 제약사 AI팀, 바이오 스타트업, 해외 포닥으로 많이 가요. 각 루트별로 어떤 준비가 필요한지 현실적으로 알려드립니다.",
  },
  {
    id: "mentor-022",
    labId: "lab-011",
    nickname: "고려대 대학원생 #19",
    cardType: "B",
    researchArea: "유전체분석",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["교수성격", "랩분위기", "인건비", "연구주제선정"],
    rating: 4.5,
    consultCount: 15,
    intro:
      "바이오인포 랩은 생물학과 전산학 배경이 섞여 있어서 팀 문화가 독특해요. 교수님과의 소통 방식, 인건비 구조, 논문 주제 자율성 등을 솔직하게 공유합니다.",
  },
  // lab-012 (성균관대 SW)
  {
    id: "mentor-023",
    labId: "lab-012",
    nickname: "성균관대 대학원생 #10",
    cardType: "A",
    researchArea: "소프트웨어공학",
    degree: "MS",
    yearsInLab: 2,
    consultTopics: ["메일작성법", "포트폴리오", "오픈소스기여", "면담준비"],
    rating: 4.6,
    consultCount: 20,
    intro:
      "SW공학 분야 교수님들은 깃허브를 진지하게 봐요. 오픈소스 기여 이력이나 프로젝트 완성도가 메일 내용보다 더 중요할 때도 있어요. 경험을 공유합니다.",
  },
  {
    id: "mentor-024",
    labId: "lab-012",
    nickname: "성균관대 대학원생 #28",
    cardType: "D",
    researchArea: "DevOps, 품질관리",
    degree: "MS",
    yearsInLab: 1,
    consultTopics: ["비서울권", "학교간판", "스펙부족", "현실조언"],
    rating: 4.2,
    consultCount: 7,
    intro:
      "성균관대 대학원은 삼성 산학 프로젝트가 많아서 취업 연계가 좋아요. '서울대·카이스트가 아니면...'이라는 걱정, 실제로 겪어보니 생각보다 괜찮습니다.",
  },
];

export function getLabById(id: string): Lab | undefined {
  return labs.find((lab) => lab.id === id);
}

export function getMentorsByLabId(labId: string): Mentor[] {
  return mentors.filter((mentor) => mentor.labId === labId);
}

export function getMentorById(id: string): Mentor | undefined {
  return mentors.find((mentor) => mentor.id === id);
}
